#ifndef TOKEN_H
#define TOKEN_H

/* Keywords. */
#define TOKEN_ARRAY 1
#define TOKEN_AUTO 2
#define TOKEN_BOOLEAN 3
#define TOKEN_CHAR 4
#define TOKEN_ELSE 5
#define TOKEN_FALSE 6
#define TOKEN_FLOAT 7
#define TOKEN_FOR 8
#define TOKEN_FUNCTION 9
#define TOKEN_IF 10
#define TOKEN_INTEGER 11
#define TOKEN_PRINT 12
#define TOKEN_RETURN 13
#define TOKEN_STRING 14
#define TOKEN_TRUE 15
#define TOKEN_VOID 16
#define TOKEN_WHILE 17

/* Operators. */
#define TOKEN_INCREMENT 18
#define TOKEN_DECREMENT 19
#define TOKEN_NOT 20
#define TOKEN_EXPONENTIATION 21
#define TOKEN_MULTIPLICATION 22
#define TOKEN_DIVISION 23
#define TOKEN_MODULO 24
#define TOKEN_ADDITION 25
#define TOKEN_SUBTRACTION 26
#define TOKEN_LESSER 27
#define TOKEN_LESSER_EQUAL 28
#define TOKEN_GREATER 29
#define TOKEN_GREATER_EQUAL 30
#define TOKEN_EQUALITY 31
#define TOKEN_INEQUALITY 32
#define TOKEN_AND 33
#define TOKEN_OR 34
#define TOKEN_ASSIGNMENT 35

/* Punctuation. */
#define TOKEN_BRACE_OPEN 36
#define TOKEN_BRACE_CLOSE 37
#define TOKEN_PAREN_OPEN 38
#define TOKEN_PAREN_CLOSE 39
#define TOKEN_BRACK_OPEN 40
#define TOKEN_BRACK_CLOSE 41
#define TOKEN_COLON 42
#define TOKEN_SEMICOLON 43
#define TOKEN_COMMA 44

/* Comments. */
#define TOKEN_COMMENT_SINGLE 45
#define TOKEN_COMMENT_MULTI 46

/* Literals. */
#define TOKEN_INTEGER_LITERAL 47
#define TOKEN_FLOAT_LITERAL 48
#define TOKEN_STRING_LITERAL 49
#define TOKEN_CHAR_LITERAL 50

/* Identifier. */
#define TOKEN_IDENTIFIER 51

#endif
